title: André Balbi Aguiar # your name (or website title) here
logo: "/images/mod_perfil.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Aeronautical Engineer, currently in the third semester of the Data Science Bachelor's program at UNIVESP.<br>
  <br>São José dos Campos - SP - Brazil
  abalbiaguiar@gmail.com<br>
  <br><a href="https://www.linkedin.com/in/drebalbi/">View My LinkedIn Profile</a><br>
  <br><a href="https://github.com/andre-balbi/andre-balbi.github.io/blob/master/CVs/cv_andre-balbi_dados_pt-br.pdf">View My Curriculum (pt)</a><br>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
